env:
  browser: true
  es2021: true

parserOptions:
  ecmaVersion: 12
  sourceType: module

extends:
  - 'airbnb-base'

rules:
  import/prefer-default-export: 0
  no-console: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
  no-await-in-loop: 0
